FROM eclipse-temurin:17-jdk-jammy

# Installation des outils
RUN apt-get update && apt-get install -y unzip wget

# Téléchargement de Gatling
WORKDIR /opt
ENV GATLING_VERSION=3.9.5
RUN wget -q -O gatling.zip https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/$GATLING_VERSION/gatling-charts-highcharts-bundle-$GATLING_VERSION-bundle.zip \
    && unzip gatling.zip \
    && mv gatling-charts-highcharts-bundle-$GATLING_VERSION gatling \
    && rm gatling.zip

# Configuration des variables d'environnement
ENV GATLING_HOME=/opt/gatling
ENV PATH=$GATLING_HOME/bin:$PATH

# Création des dossiers pour éviter les erreurs de permission
RUN mkdir -p /opt/gatling/results /opt/gatling/user-files

WORKDIR /opt/gatling
ENTRYPOINT ["gatling.sh"]